# 2026-01-08
# Study E/P at individual cut level

[parameters]
gOre_threshold = 25 # MeV
muon_threshold = 25 # MeV
pion_threshold = 25 # MeV
proton_threshold = 50 # MeV
flash_low_t =  0.0 # µs
flash_high_t = 1.6 # µs
fiducial_xdist_pos = 25 # cm
fiducial_xdist_neg = 25 # cm
fiducial_ydist_pos = 25 # cm
fiducial_ydist_neg = 25 # cm
fiducial_zdist_pos = 50 # cm
fiducial_zdist_neg = 30 # cm
pion_mass_threshold = 0.4 # fraction of π0 mass
photon_vertex_resolution = 150 # cm
flash_pe_neutron_scaling = 0.01
angle_neutron_scaling = 1.0

[general]
output = "/exp/sbnd/data/users/sc5303/NCDelta/gOre_1g0p_1g1p_single"
fsthresh = [
  "@gOre_threshold",
  "@muon_threshold",
  "@pion_threshold",
  "@proton_threshold",
]
pidfn = "gOre_pid"

# Categories are for topology

[[category]] # Topo 1g0p
cuts = [
  { name = "neutrino"                                                 },
  { name = "containment_cut"                                          },
  { name = "fiducial_cut"                                             },
  { name = "single_photon",       parameters = [ "@gOre_threshold" ]  },
  { name = "no_electrons",        parameters = [ "@gOre_threshold" ]  },
  { name = "no_muons",            parameters = [ "@muon_threshold" ]  },
  { name = "no_charged_pions",    parameters = [ "@pion_threshold" ]  },
  { name = "no_protons",          parameters = [ "@proton_threshold" ]},
]

[[category]] # Topo 1g1p
cuts = [
  { name = "neutrino"                                                 },
  { name = "containment_cut"                                          },
  { name = "fiducial_cut"                                             },
  { name = "single_photon",       parameters = [ "@gOre_threshold" ]  },
  { name = "no_electrons",        parameters = [ "@gOre_threshold" ]  },
  { name = "no_muons",            parameters = [ "@muon_threshold" ]  },
  { name = "no_charged_pions",    parameters = [ "@pion_threshold" ]  },
  { name = "single_proton",       parameters = [ "@proton_threshold" ]},
]

[[category]] # contained, fiducial, single photon
cuts = [
  { name = "neutrino"                                                 },
  { name = "containment_cut"                                          },
  { name = "fiducial_cut"                                             },
  { name = "single_photon",        parameters = [ "@gOre_threshold" ] },
  { name = "no_electrons",         parameters = [ "@gOre_threshold" ] },
  { name = "no_muons",             parameters = [ "@muon_threshold" ] },
  { name = "no_charged_pions",     parameters = [ "@pion_threshold" ] },
]

[[category]] # single photon
cuts = [
  { name = "neutrino"                                                 },
  { name = "single_photon",        parameters = [ "@gOre_threshold" ] },
  { name = "no_electrons",         parameters = [ "@gOre_threshold" ] },
  { name = "no_muons",             parameters = [ "@muon_threshold" ] },
  { name = "no_charged_pions",     parameters = [ "@pion_threshold" ] },
]

[[category]] # contained, fiducial, single electron
cuts = [
  { name = "neutrino"                                                 },
  { name = "containment_cut"                                          },
  { name = "fiducial_cut"                                             },
  { name = "single_electron",      parameters = [ "@gOre_threshold" ] },
  { name = "no_photons",           parameters = [ "@gOre_threshold" ] },
  { name = "no_muons",             parameters = [ "@muon_threshold" ] },
  { name = "no_charged_pions",     parameters = [ "@pion_threshold" ] },
]

[[category]] # single electron
cuts = [
  { name = "neutrino"                                                 },
  { name = "single_electron",      parameters = [ "@gOre_threshold" ] },
  { name = "no_photons",           parameters = [ "@gOre_threshold" ] },
  { name = "no_muons",             parameters = [ "@muon_threshold" ] },
  { name = "no_charged_pions",     parameters = [ "@pion_threshold" ] },
]

[[category]] # contained, fiducial, dual photon
cuts = [
  { name = "neutrino"                                                 },
  { name = "containment_cut"                                          },
  { name = "fiducial_cut"                                             },
  { name = "dual_photon",          parameters = [ "@gOre_threshold" ] },
  { name = "no_electrons",         parameters = [ "@gOre_threshold" ] },
  { name = "no_muons",             parameters = [ "@muon_threshold" ] },
  { name = "no_charged_pions",     parameters = [ "@pion_threshold" ] },
]

[[category]] # dual photon
cuts = [
  { name = "neutrino"                                                 },
  { name = "dual_photon",          parameters = [ "@gOre_threshold" ] },
  { name = "no_electrons",         parameters = [ "@gOre_threshold" ] },
  { name = "no_muons",             parameters = [ "@muon_threshold" ] },
  { name = "no_charged_pions",     parameters = [ "@pion_threshold" ] },
]

[[category]] # NC
cuts = [
  { name = "neutrino" },
  { name = "!iscc"    },
]

[[category]] # CC
cuts = [
  { name = "neutrino" },
]

[[category]] # cosmic
cuts = [
  { name = "!neutrino" },
]

[[sample]]
name = "simulation"
path = "/pnfs/sbnd/persistent/users/mueller/MCP2025B/simulation/mc1e20/input*-reweighted.flat.caf.root"
ismc = true
disable = false


[[tree]]
name = "Total"
sim_only = false
add_systematics = true
mode = "reco"
cut = [

]
branch = [
  # MC Truth
  { name = "cc",               type = "mctruth" },
  { name = "pdg",              type = "mctruth" },
  { name = "interaction_mode", type = "mctruth" },
  { name = "interaction_type", type = "mctruth" },
  { name = "neutrino_energy",  type = "mctruth" },
  { name = "baryon_res_code",  type = "mctruth" },
  { name = "mc_category",      type = "mctruth", parameters = [ "@gOre_threshold", "@muon_threshold", "@proton_threshold", "@pion_threshold",
                                                                "@fiducial_xdist_pos", "@fiducial_xdist_neg", "@fiducial_ydist_pos", "@fiducial_ydist_neg", "@fiducial_zdist_pos", "@fiducial_zdist_neg", ] },
  # True
  { name = "neutrino_id",   type = "true" },
  { name = "category",      type = "true" },
  { name = "gOre_category", type = "true", parameters = [ "@gOre_threshold", "@muon_threshold", "@proton_threshold", "@pion_threshold" ] },
  # Both
  { name = "fiducial",       type = "both" },
  { name = "containment",    type = "both" },
  { name = "flash",          type = "both" },
  { name = "gOre_topology",  type = "both", parameters = [ "@gOre_threshold", "@muon_threshold", "@pion_threshold" ] },
  { name = "flash_time",     type = "reco" },
  { name = "n_primary_showers", type = "both", parameters = [ "@gOre_threshold" ] },
  { name = "n_protons",         type = "both", parameters = [ "@proton_threshold" ] },
  { name = "photon_multiplicity", type = "both", parameters = [ "@gOre_threshold" ] },
  { name = "electron_multiplicity", type = "both", parameters = [ "@gOre_threshold" ] },
  { name = "muon_multiplicity",   type = "both", parameters = [ "@muon_threshold" ] },
  { name = "pion_multiplicity",   type = "both", parameters = [ "@pion_threshold" ] },
  { name = "proton_multiplicity",   type = "both", parameters = [ "@proton_threshold" ] },
]

[[tree]] # signal (NC ∆->Nγ) 1g0p
name = "signal_1g0p"
sim_only = true
mode = "true"
add_systematics = true
cut = [
    { name = "neutrino",                    type = "true"                                       },    
    { name = "fiducial_cut",                type = "true"                                       },
    { name = "containment_cut",             type = "true"                                       },
    { name = "single_photon",               type = "true", parameters = [ "@gOre_threshold" ]   },
    { name = "no_electrons",                type = "true", parameters = [ "@gOre_threshold" ]   },
    { name = "no_muons",                    type = "true", parameters = [ "@muon_threshold" ]   },
    { name = "no_charged_pions",            type = "true", parameters = [ "@pion_threshold" ]   },
    { name = "no_protons",                  type = "true", parameters = [ "@proton_threshold" ] },
    { name = "has_nc_delta_ng_interaction", type = "event", decrements_exposure = false         },
]

branch = [
  # MC Truth
  { name = "cc",               type = "mctruth" },
  { name = "pdg",              type = "mctruth" },
  { name = "interaction_mode", type = "mctruth" },
  { name = "interaction_type", type = "mctruth" },
  { name = "neutrino_energy",  type = "mctruth" },
  { name = "baryon_res_code",  type = "mctruth" },
  { name = "mc_category",      type = "mctruth", parameters = [ "@gOre_threshold", "@muon_threshold", "@proton_threshold", "@pion_threshold",
                                                                "@fiducial_xdist_pos", "@fiducial_xdist_neg", "@fiducial_ydist_pos", "@fiducial_ydist_neg", "@fiducial_zdist_pos", "@fiducial_zdist_neg", ] },
  # True
  { name = "neutrino_id",   type = "true" },
  { name = "category",      type = "true" },
  { name = "gOre_category", type = "true", parameters = [ "@gOre_threshold", "@muon_threshold", "@proton_threshold", "@pion_threshold" ] },
  # Both
  { name = "fiducial",       type = "both" },
  { name = "containment",    type = "both" },
  { name = "flash",          type = "both" },
  { name = "gOre_topology",  type = "both", parameters = [ "@gOre_threshold", "@muon_threshold", "@pion_threshold" ] },
  { name = "n_primary_showers", type = "both", parameters = [ "@gOre_threshold" ] },
  { name = "n_protons",         type = "both", parameters = [ "@proton_threshold" ] },
  { name = "photon_multiplicity", type = "both", parameters = [ "@gOre_threshold" ] },
  { name = "electron_multiplicity", type = "both", parameters = [ "@gOre_threshold" ] },
  { name = "muon_multiplicity",   type = "both", parameters = [ "@muon_threshold" ] },
  { name = "pion_multiplicity",   type = "both", parameters = [ "@pion_threshold" ] },
  { name = "proton_multiplicity",   type = "both", parameters = [ "@proton_threshold" ] },
]

[[tree]] # signal (NC ∆->Nγ) 1g1p
name = "signal_1g1p"
sim_only = true
mode = "true"
add_systematics = true
cut = [
    { name = "neutrino",                    type = "true"                                       },    
    { name = "fiducial_cut",                type = "true"                                       },
    { name = "containment_cut",             type = "true"                                       },
    { name = "single_photon",               type = "true", parameters = [ "@gOre_threshold" ]   },
    { name = "no_electrons",                type = "true", parameters = [ "@gOre_threshold" ]   },
    { name = "no_muons",                    type = "true", parameters = [ "@muon_threshold" ]   },
    { name = "no_charged_pions",            type = "true", parameters = [ "@pion_threshold" ]   },
    { name = "single_proton",               type = "true", parameters = [ "@proton_threshold" ] },
    { name = "has_nc_delta_ng_interaction", type = "event", decrements_exposure = false         },
]
branch = [
  # MC Truth
  { name = "cc",               type = "mctruth" },
  { name = "pdg",              type = "mctruth" },
  { name = "interaction_mode", type = "mctruth" },
  { name = "interaction_type", type = "mctruth" },
  { name = "neutrino_energy",  type = "mctruth" },
  { name = "baryon_res_code",  type = "mctruth" },
  { name = "mc_category",      type = "mctruth", parameters = [ "@gOre_threshold", "@muon_threshold", "@proton_threshold", "@pion_threshold",
                                                                "@fiducial_xdist_pos", "@fiducial_xdist_neg", "@fiducial_ydist_pos", "@fiducial_ydist_neg", "@fiducial_zdist_pos", "@fiducial_zdist_neg", ] },
  # True
  { name = "neutrino_id",   type = "true" },
  { name = "category",      type = "true" },
  { name = "gOre_category", type = "true", parameters = [ "@gOre_threshold", "@muon_threshold", "@proton_threshold", "@pion_threshold" ] },
  # Both
  { name = "fiducial",       type = "both" },
  { name = "containment",    type = "both" },
  { name = "flash",          type = "both" },
  { name = "gOre_topology",  type = "both", parameters = [ "@gOre_threshold", "@muon_threshold", "@pion_threshold" ] },
  { name = "n_primary_showers", type = "both", parameters = [ "@gOre_threshold" ] },
  { name = "n_protons",         type = "both", parameters = [ "@proton_threshold" ] },
  { name = "photon_multiplicity", type = "both", parameters = [ "@gOre_threshold" ] },
  { name = "electron_multiplicity", type = "both", parameters = [ "@gOre_threshold" ] },
  { name = "muon_multiplicity",   type = "both", parameters = [ "@muon_threshold" ] },
  { name = "pion_multiplicity",   type = "both", parameters = [ "@pion_threshold" ] },
  { name = "proton_multiplicity",   type = "both", parameters = [ "@proton_threshold" ] },
]

[[tree]] # True 1g0p
name = "true_1g0p"
sim_only = true
mode = "true"
add_systematics = true
cut = [
    { name = "neutrino",                    type = "true"                                       },    
    { name = "fiducial_cut",                type = "true"                                       },
    { name = "containment_cut",             type = "true"                                       },
    { name = "single_photon",               type = "true", parameters = [ "@gOre_threshold" ]   },
    { name = "no_electrons",                type = "true", parameters = [ "@gOre_threshold" ]   },
    { name = "no_muons",                    type = "true", parameters = [ "@muon_threshold" ]   },
    { name = "no_charged_pions",            type = "true", parameters = [ "@pion_threshold" ]   },
    { name = "no_protons",                  type = "true", parameters = [ "@proton_threshold" ] },
]
branch = [
  # MC Truth
  { name = "cc",               type = "mctruth" },
  { name = "pdg",              type = "mctruth" },
  { name = "interaction_mode", type = "mctruth" },
  { name = "interaction_type", type = "mctruth" },
  { name = "neutrino_energy",  type = "mctruth" },
  { name = "baryon_res_code",  type = "mctruth" },
  { name = "mc_category",      type = "mctruth", parameters = [ "@gOre_threshold", "@muon_threshold", "@proton_threshold", "@pion_threshold",
                                                                "@fiducial_xdist_pos", "@fiducial_xdist_neg", "@fiducial_ydist_pos", "@fiducial_ydist_neg", "@fiducial_zdist_pos", "@fiducial_zdist_neg", ] },
  # True
  { name = "neutrino_id",   type = "true" },
  { name = "category",      type = "true" },
  { name = "gOre_category", type = "true", parameters = [ "@gOre_threshold", "@muon_threshold", "@proton_threshold", "@pion_threshold" ] },
  # Both
  { name = "fiducial",       type = "both" },
  { name = "containment",    type = "both" },
  { name = "flash",          type = "both" },
  { name = "gOre_topology",  type = "both", parameters = [ "@gOre_threshold", "@muon_threshold", "@pion_threshold" ] },
  { name = "n_primary_showers", type = "both", parameters = [ "@gOre_threshold" ] },
  { name = "n_protons",         type = "both", parameters = [ "@proton_threshold" ] },
  { name = "photon_multiplicity", type = "both", parameters = [ "@gOre_threshold" ] },
  { name = "electron_multiplicity", type = "both", parameters = [ "@gOre_threshold" ] },
  { name = "muon_multiplicity",   type = "both", parameters = [ "@muon_threshold" ] },
  { name = "pion_multiplicity",   type = "both", parameters = [ "@pion_threshold" ] },
  { name = "proton_multiplicity",   type = "both", parameters = [ "@proton_threshold" ] },
]

[[tree]] # true 1g1p
name = "true_1g1p"
sim_only = true
mode = "true"
add_systematics = true
cut = [
    { name = "neutrino",                    type = "true"                                       },    
    { name = "fiducial_cut",                type = "true"                                       },
    { name = "containment_cut",             type = "true"                                       },
    { name = "single_photon",               type = "true", parameters = [ "@gOre_threshold" ]   },
    { name = "no_electrons",                type = "true", parameters = [ "@gOre_threshold" ]   },
    { name = "no_muons",                    type = "true", parameters = [ "@muon_threshold" ]   },
    { name = "no_charged_pions",            type = "true", parameters = [ "@pion_threshold" ]   },
    { name = "single_proton",               type = "true", parameters = [ "@proton_threshold" ] },
]
branch = [
  # MC Truth
  { name = "cc",               type = "mctruth" },
  { name = "pdg",              type = "mctruth" },
  { name = "interaction_mode", type = "mctruth" },
  { name = "interaction_type", type = "mctruth" },
  { name = "neutrino_energy",  type = "mctruth" },
  { name = "baryon_res_code",  type = "mctruth" },
  { name = "mc_category",      type = "mctruth", parameters = [ "@gOre_threshold", "@muon_threshold", "@proton_threshold", "@pion_threshold",
                                                                "@fiducial_xdist_pos", "@fiducial_xdist_neg", "@fiducial_ydist_pos", "@fiducial_ydist_neg", "@fiducial_zdist_pos", "@fiducial_zdist_neg", ] },
  # True
  { name = "neutrino_id",   type = "true" },
  { name = "category",      type = "true" },
  { name = "gOre_category", type = "true", parameters = [ "@gOre_threshold", "@muon_threshold", "@proton_threshold", "@pion_threshold" ] },
  # Both
  { name = "fiducial",       type = "both" },
  { name = "containment",    type = "both" },
  { name = "flash",          type = "both" },
  { name = "gOre_topology",  type = "both", parameters = [ "@gOre_threshold", "@muon_threshold", "@pion_threshold" ] },
  { name = "n_primary_showers", type = "both", parameters = [ "@gOre_threshold" ] },
  { name = "n_protons",         type = "both", parameters = [ "@proton_threshold" ] },
  { name = "photon_multiplicity", type = "both", parameters = [ "@gOre_threshold" ] },
  { name = "electron_multiplicity", type = "both", parameters = [ "@gOre_threshold" ] },
  { name = "muon_multiplicity",   type = "both", parameters = [ "@muon_threshold" ] },
  { name = "pion_multiplicity",   type = "both", parameters = [ "@pion_threshold" ] },
  { name = "proton_multiplicity",   type = "both", parameters = [ "@proton_threshold" ] },
]
